<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Home Gutenverse Consultation Doctor', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-QHMNbD","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="QHMNbD"><section class="wp-block-gutenverse-section guten-element guten-section guten-QHMNbD layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":62,"Tablet":null,"Mobile":null},"elementId":"guten-RwyfBw","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"position":[],"repeat":[],"size":[]},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":18,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/quinnie-pattern-qkpsly.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"blendMode":{"Desktop":"normal"}},"opacity":"0.1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":"23.999999999999996","g":"22.000000000000004","b":"43","a":"0.14"},"horizontal":"0","vertical":"3","blur":"35","spread":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-120","right":"5","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-100","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":null}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RwyfBw animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="RwyfBw"><div class="guten-background-overlay"></div><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-2NVWlC","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false}} -->
<div class="section-wrapper" data-id="2NVWlC"><section class="wp-block-gutenverse-section guten-element guten-section guten-2NVWlC layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.9,"Mobile":100},"elementId":"guten-DZE4LK","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DZE4LK"><div class="guten-column-wrapper" data-id="DZE4LK"><!-- wp:gutenverse/heading {"elementId":"guten-C8eSSa","type":3,"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"a89b1a5"},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","bottom":""}},"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":[],"Desktop":[]},"positioningType":{"Mobile":"full"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-C8eSSa">How Can I Help You?</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-O6rFXX","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"28"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":200},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"600","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-O6rFXX animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Curabitur ullamcorper ultricies nisi nam eget dui. Etiam rhoncus maecenas tempus tellus eget condimentum rhoncus quam semper.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-RhoW2R","content":"Explore Service","url":"#","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0},"image":[]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconPosition":"after","iconSpacing":{"Desktop":"10","Mobile":""},"iconSize":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"theme-4"},"iconColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"f04d15a","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverIconColor":{"type":"variable","id":"theme-3"},"hoverTextColor":{"type":"variable","id":"theme-3"},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element guten-button-wrapper guten-RhoW2R"><a class="guten-button guten-button-sm" href="#"><span>Explore Service</span><i class="fa-lg gtn gtn-right-arrow-light"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":45.1,"Mobile":null},"elementId":"guten-fTM9pC","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"80"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[],"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fTM9pC"><div class="guten-column-wrapper" data-id="fTM9pC"><!-- wp:gutenverse/icon-list {"elementId":"guten-bo8Wyf","spaceBetween":{"Desktop":"12","Tablet":"","Mobile":"20"},"verticalAlign":"center","iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"18","Mobile":"16"},"textColor":{"type":"variable","id":"text"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":""}}},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element guten-icon-list guten-bo8Wyf"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-uB9lIU"} -->
<div class="guten-element guten-icon-list-item guten-uB9lIU"><a id="guten-uB9lIU"><i class="fas fa-check-circle"></i><span class="list-text ">Breast Implant</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-29XYqs"} -->
<div class="guten-element guten-icon-list-item guten-29XYqs"><a id="guten-29XYqs"><i class="fas fa-check-circle"></i><span class="list-text ">Body Shaping</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-pGe6xT"} -->
<div class="guten-element guten-icon-list-item guten-pGe6xT"><a id="guten-pGe6xT"><i class="fas fa-check-circle"></i><span class="list-text ">Buttocks Reshape</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-mOIozd"} -->
<div class="guten-element guten-icon-list-item guten-mOIozd"><a id="guten-mOIozd"><i class="fas fa-check-circle"></i><span class="list-text ">Botox Injection</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-IjlX3b"} -->
<div class="guten-element guten-icon-list-item guten-IjlX3b"><a id="guten-IjlX3b"><i class="fas fa-check-circle"></i><span class="list-text ">Blepharoplasty</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":38,"Tablet":null,"Mobile":null},"elementId":"guten-olaXRL","background":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":"24.00000126050871","g":"22.000001393193834","b":"43.0000000000001","a":"0.14"},"horizontal":"0","vertical":"3","blur":"35","spread":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-120","right":"0","bottom":"0","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"50","bottom":"40","left":"50"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-olaXRL animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="olaXRL"><!-- wp:gutenverse/icon-box {"elementId":"guten-YBGGQo","separateButtonLink":false,"title":"Consultation With Our Doctor","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididuntut labore","iconType":"none","icon":"","iconSize":{"Desktop":""},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Tablet":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5"},"descMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"zIndex":{"Tablet":1},"parentSelector":".guten-YBGGQo:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-YBGGQo guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Consultation With Our Doctor</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididuntut labore</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-G90Amn","url":"#","separateButtonLink":false,"title":"(+62)81 2876 0851","description":"","hasGlobalLink":true,"icon":"gtn gtn-phone1-light","iconSize":{"Desktop":"24","Mobile":"22"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"iconStyleMode":"color","iconColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"theme-4"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"2"}},"Tablet":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"960b046","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"descTypography":{"type":"variable","id":"text"},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Tablet":1},"positioningType":{"Mobile":"inline"},"parentSelector":".guten-G90Amn:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-G90Amn guten-icon-box icon-position-left"><a class="" href="#"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">(+62)81 2876 0851</h2></div></div></a></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
