<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Search Gutenverse Hero', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-3L05JD","background":{"type":"default","color":[],"image":{"Desktop":{"id":598,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/cosmetician-gives-face-botox-injections-quinnie.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false,"blendMode":{"Desktop":"normal"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"-250","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-3"}},"opacity":"0.8","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","right":"0","bottom":"120","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"80","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"10","bottom":"60","left":"10"}}}} -->
<div class="section-wrapper" data-id="3L05JD"><section class="wp-block-gutenverse-section guten-element guten-section guten-3L05JD layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-IG7Ar2","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Tablet":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-IG7Ar2"><div class="guten-column-wrapper" data-id="IG7Ar2"><!-- wp:gutenverse/heading {"elementId":"guten-jJCRb7","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_primary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"spacing":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"25"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"full"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-jJCRb7">Search Result</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/search {"elementId":"guten-IXxYjP","positioningType":{"Desktop":"inline"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"","right":"","bottom":""}},"Tablet":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputPlaceholder":"Search","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"32","right":"32","top":"18","bottom":"18"}},"Mobile":{"unit":"px","dimension":{"bottom":"16","top":"16","right":"30","left":"30"}},"Tablet":[]},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":[]},"inputHeight":{"Desktop":"","Mobile":""},"inputWidth":{"Desktop":{"unit":"px","point":"450"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"50","right":"0","top":"50","bottom":"0"}}},"all":{"type":"none","width":null,"color":""}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"Tablet":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"left":""}},"Mobile":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"alignContent":{"Mobile":"center","Desktop":"center"},"className":"guten-icon"} -->
<div class="guten-element guten-IXxYjP guten-search guten-icon"><form class="gutenverse-search-form"><div class="search-input-container"><input type="search" placeholder="Search" name="s" class="gutenverse-search gutenverse-search-input"/></div><!-- wp:gutenverse/button {"elementId":"guten-ofsZKS","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"buttonHeight":{"Desktop":"62","Mobile":"52"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"buttonBackground":{"color":{"type":"variable","id":"theme-4"},"type":"default","position":{"Mobile":"default"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"50","left":"0"}}},"all":{"type":"none","width":null,"color":""}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"none"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"px","point":"320"}}} -->
<div class="guten-element guten-button-wrapper guten-ofsZKS"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
