<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Our Doctor Gutenverse Our Doctor', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-Tq0Ec1","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"position":[],"repeat":[],"size":[],"videoPlayOnMobile":false},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"80","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"60","left":"0"}}}} -->
<div class="section-wrapper" data-id="Tq0Ec1"><section class="wp-block-gutenverse-section guten-element guten-section guten-Tq0Ec1 layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-0DaPbi","background":{"type":"default","color":[],"image":[]},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0DaPbi"><div class="guten-column-wrapper" data-id="0DaPbi"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-Tqzwc4","alignText":{"Desktop":"center"},"subTag":"h5","text":"Meet Our Qualified Doctors","focusText":"","subText":"Our Doctors","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"0d5454c","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"subPadding":{"Desktop":[],"Mobile":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-advanced-heading guten-Tqzwc4"><h5 class="heading-subtitle">Our Doctors</h5><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Meet Our Qualified Doctors</span><span class="heading-focus"></span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-7pYnIS","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"28","bottom":"0","left":"28"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element gutenverse-text-editor guten-7pYnIS"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":1290},"isChild":true,"gap":"no","elementId":"guten-uwpFmF","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"zIndex":{"Desktop":1}} -->
<div class="section-wrapper" data-id="uwpFmF"><section class="wp-block-gutenverse-section guten-element guten-section guten-uwpFmF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":null},"elementId":"guten-VHZq3M","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VHZq3M animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="VHZq3M"><!-- wp:gutenverse/team {"elementId":"guten-NXAfB7","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":405,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-asjghne-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"imageBorderResponsive":{"Mobile":{"radius":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-NXAfB7"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-asjghne-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-PGXvTQ","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-PGXvTQ circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-gUB3NG"} -->
<div class="guten-element guten-social-icon guten-gUB3NG facebook"><a id="guten-gUB3NG" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-bFCdtO"} -->
<div class="guten-element guten-social-icon guten-bFCdtO twitter"><a id="guten-bFCdtO" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-1hmxfh"} -->
<div class="guten-element guten-social-icon guten-1hmxfh instagram"><a id="guten-1hmxfh" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-4JEh5H","separateButtonLink":false,"title":"Shreya Pearce","titleTag":"h3","description":"Aesthetic Surgery","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"zIndex":{"Desktop":1},"positioningType":{"Tablet":"default"},"parentSelector":".guten-4JEh5H:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-4JEh5H guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Shreya Pearce</h3><p class="icon-box-description">Aesthetic Surgery</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.34,"Tablet":50},"elementId":"guten-8USNq3","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8USNq3 animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="8USNq3"><!-- wp:gutenverse/team {"elementId":"guten-DOe2Ha","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":406,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-tmrdqf-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-DOe2Ha"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-tmrdqf-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-vcO8ZR","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-vcO8ZR circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-NRdkTf"} -->
<div class="guten-element guten-social-icon guten-NRdkTf facebook"><a id="guten-NRdkTf" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-4Vsd82"} -->
<div class="guten-element guten-social-icon guten-4Vsd82 twitter"><a id="guten-4Vsd82" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-PlpNey"} -->
<div class="guten-element guten-social-icon guten-PlpNey instagram"><a id="guten-PlpNey" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-StvRX2","separateButtonLink":false,"title":"Sophie Hodges","titleTag":"h3","description":"CEO Quinnie","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":1},"parentSelector":".guten-StvRX2:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-StvRX2 guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Sophie Hodges</h3><p class="icon-box-description">CEO Quinnie</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100},"elementId":"guten-weYMfZ","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"26","left":"26","top":"4"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":400}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-weYMfZ animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="weYMfZ"><!-- wp:gutenverse/team {"elementId":"guten-0E8r6X","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":407,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-bkulzsw-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-0E8r6X"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-bkulzsw-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-4xhalb","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-4xhalb circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-7c3E3l"} -->
<div class="guten-element guten-social-icon guten-7c3E3l facebook"><a id="guten-7c3E3l" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-sgfMjT"} -->
<div class="guten-element guten-social-icon guten-sgfMjT twitter"><a id="guten-sgfMjT" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-SUDByo"} -->
<div class="guten-element guten-social-icon guten-SUDByo instagram"><a id="guten-SUDByo" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-Jgb3WQ","separateButtonLink":false,"title":"Eren Steadman","titleTag":"h3","description":"Aesthetic Surgery","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":1},"parentSelector":".guten-Jgb3WQ:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-Jgb3WQ guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Eren Steadman</h3><p class="icon-box-description">Aesthetic Surgery</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":1290},"isChild":true,"gap":"no","elementId":"guten-zaWqre","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":1}} -->
<div class="section-wrapper" data-id="zaWqre"><section class="wp-block-gutenverse-section guten-element guten-section guten-zaWqre layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":null},"elementId":"guten-UpKOSY","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-UpKOSY animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="UpKOSY"><!-- wp:gutenverse/team {"elementId":"guten-cfgtob","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":652,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-diana-carver-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"imageBorderResponsive":{"Mobile":{"radius":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-cfgtob"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/doctor-diana-carver-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-vcRtgw","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-vcRtgw circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-WzFEjt"} -->
<div class="guten-element guten-social-icon guten-WzFEjt facebook"><a id="guten-WzFEjt" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-VrKjnO"} -->
<div class="guten-element guten-social-icon guten-VrKjnO twitter"><a id="guten-VrKjnO" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-fX3qmm"} -->
<div class="guten-element guten-social-icon guten-fX3qmm instagram"><a id="guten-fX3qmm" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-J1V2tl","separateButtonLink":false,"title":"Diana Carver","titleTag":"h3","description":"Aesthetic Surgery","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"zIndex":{"Desktop":1},"positioningType":{"Tablet":"default"},"parentSelector":".guten-J1V2tl:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-J1V2tl guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Diana Carver</h3><p class="icon-box-description">Aesthetic Surgery</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.34,"Tablet":50},"elementId":"guten-t6AH0E","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-t6AH0E animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="t6AH0E"><!-- wp:gutenverse/team {"elementId":"guten-VpNT9w","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":653,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/cosmet-ammy-donkley-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-VpNT9w"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/cosmet-ammy-donkley-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-6jhJf5","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-6jhJf5 circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-rMz1Sf"} -->
<div class="guten-element guten-social-icon guten-rMz1Sf facebook"><a id="guten-rMz1Sf" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-YT8XSk"} -->
<div class="guten-element guten-social-icon guten-YT8XSk twitter"><a id="guten-YT8XSk" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-O9Slf9"} -->
<div class="guten-element guten-social-icon guten-O9Slf9 instagram"><a id="guten-O9Slf9" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-lByPgK","separateButtonLink":false,"title":"Emmy Dunkley","titleTag":"h3","description":"Asthetic Surgery","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":1},"parentSelector":".guten-lByPgK:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-lByPgK guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Emmy Dunkley</h3><p class="icon-box-description">Asthetic Surgery</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100},"elementId":"guten-HcCVNr","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"26","left":"26","top":"4"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":400}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HcCVNr animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="HcCVNr"><!-- wp:gutenverse/team {"elementId":"guten-6gS2SO","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px","point":""}},"src":{"id":654,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/female-doctor-with-stethoscope-quinnie.webp"},"lazy":true,"name":"","job":"","showDesc":true,"description":"","phone":"+1 (234) 567-879","email":"info@example.com","profilePadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":[]},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"background":{"type":"default","color":[],"image":[]},"profileBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.3215686274509804},"image":[],"position":[],"repeat":[],"size":[]},"profileBackgroundHover":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgHeight":{"Desktop":{"unit":"px","point":"510"},"Tablet":{"unit":"px","point":"430"},"Mobile":{"unit":"px","point":"400"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverBgColor":{"type":"default","color":{"r":24,"g":22,"b":43,"a":0.5}},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-6gS2SO"><div class="profile-box"><div class="profile-card card-overlay default"><img loading="lazy" src="' . esc_url( QUINNIE_URI ) . 'assets/img/female-doctor-with-stethoscope-quinnie.webp" alt=""/><div class="profile-body center"><h3 class="profile-title " aria-label="Profile Name"></h3><p class="profile-sub" aria-label="Profile Job"></p><p class="profile-desc" aria-label="Team Description"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-EiBATg","iconSize":{"Desktop":{"point":"20","unit":"px"}},"gap":{"Desktop":"20"},"shape":"circle","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-4"},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"hoverIconColor":{"type":"variable","id":"theme-4"},"hoverBgColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-social-icons guten-EiBATg circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-YXLx7o"} -->
<div class="guten-element guten-social-icon guten-YXLx7o facebook"><a id="guten-YXLx7o" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-x1kXgJ"} -->
<div class="guten-element guten-social-icon guten-x1kXgJ twitter"><a id="guten-x1kXgJ" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-MffRhI"} -->
<div class="guten-element guten-social-icon guten-MffRhI instagram"><a id="guten-MffRhI" href="#"><i class="fab fa-instagram"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-QnY42V","separateButtonLink":false,"title":"Vicky Sharples","titleTag":"h3","description":"Aesthetic Surgery","iconType":"none","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"25","bottom":"30","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"containerBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"containerBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"a89b1a5"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"background":{"type":"default","color":[],"image":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-160","right":"30","bottom":"0","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"-130","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"-120","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":1},"parentSelector":".guten-QnY42V:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-QnY42V guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Vicky Sharples</h3><p class="icon-box-description">Aesthetic Surgery</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
