<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Appointment Gutenverse Appointment', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-2g4d6p","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"position":[],"repeat":[],"size":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"0","bottom":"80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"10","bottom":"60","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="2g4d6p"><section class="wp-block-gutenverse-section guten-element guten-section guten-2g4d6p layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-ZY8wTy","order":{"Tablet":2},"background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"position":[],"repeat":[],"size":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":"23.999999999999996","g":"22.000000000000004","b":"43","a":"0.14"},"horizontal":"0","vertical":"3","blur":"30","spread":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZY8wTy"><div class="guten-column-wrapper" data-id="ZY8wTy"><!-- wp:gutenverse/form-builder {"elementId":"guten-wtepQf","formId":{"label":"Form Appointment","value":1039}} -->
<form style="display:none" class="guten-element guten-form-builder guten-wtepQf" data-form-id="1039"><!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-3haLgc"} -->
<div class="section-wrapper" data-id="3haLgc"><section class="wp-block-gutenverse-section guten-element guten-section guten-3haLgc layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-GmyrJ3"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GmyrJ3"><div class="guten-column-wrapper" data-id="GmyrJ3"><!-- wp:gutenverse/form-input-text {"elementId":"guten-5sX1ez","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"text"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-5sX1ez hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-hLHoZn","margin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="hLHoZn"><section class="wp-block-gutenverse-section guten-element guten-section guten-hLHoZn layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-iPtZrS","margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-iPtZrS"><div class="guten-column-wrapper" data-id="iPtZrS"><!-- wp:gutenverse/form-input-email {"elementId":"guten-FYfcN4","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-FYfcN4 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-W6reUq","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-W6reUq"><div class="guten-column-wrapper" data-id="W6reUq"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-2fkPVH","showLabel":false,"showHelper":false,"labelWidth":{"Desktop":"62"},"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"inputPlaceholder":"Your Phone Number","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-2fkPVH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Phone Number" name="input-phone" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="\+[0-9]+[0-9\s\-]*"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-select {"elementId":"guten-jrH04o","showLabel":false,"inputPlaceholder":"Select Services","showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"selectOptions":[{"value":"option-1","label":"Rhinoplasty","_key":"r8zD6S"},{"value":"option-2","label":"Botox Injection","_key":"QrpxPX"},{"value":"option-3","label":"Breast Implant","_key":"t3DH9m"},{"value":"option-3","label":"Facelift","_key":"raQxnl"},{"value":"option-3","label":"Body Shaping","_key":"qTCzlR"},{"value":"option-3","label":"Buttocks Reshape","_key":"hQyqqh"}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","right":"23","bottom":"13","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"placeholderBgColor":{"Desktop":{"type":"variable","id":"white"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]}},"choicesColorNormal":{"Desktop":{"type":"variable","id":"theme-5"}},"choicesColorHover":{"Desktop":{"type":"variable","id":"white"}},"choicesBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"choicesBgColorHover":{"Desktop":{"type":"variable","id":"theme-4"}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-jrH04o hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="input-select" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Select Services</option><option value="option-1">Rhinoplasty</option><option value="option-2">Botox Injection</option><option value="option-3">Breast Implant</option><option value="option-3">Facelift</option><option value="option-3">Body Shaping</option><option value="option-3">Buttocks Reshape</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select -->

<!-- wp:gutenverse/form-input-date {"elementId":"guten-bPKPLO","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"inputPlaceholder":"Select Date","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-date guten-form-input guten-input-position-top guten-bPKPLO hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;date&quot;}" data-date="{&quot;dateFormat&quot;:&quot;F j, Y&quot;}" placeholder="Select Date" name="input-date" class="gutenverse-input gutenverse-input-date" type="text"/><div class="validation-error"></div></div></div>
<!-- /wp:gutenverse/form-input-date -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-IwMzPc","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"inputHeight":{"Desktop":"200"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"10"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-IwMzPc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-hp3k1U","content":"Make Appointment","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"color":{"type":"variable","id":"3eec7ca"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"16","bottom":"16"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-hp3k1U"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Make Appointment</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-7YMHAy","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"80"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"50","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7YMHAy"><div class="guten-column-wrapper" data-id="7YMHAy"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-UyfgMi","subTag":"h5","text":"Make an Appointment","focusText":"","subText":"Book Now","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"mainPadding":{"Desktop":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"0d5454c","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"subPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-advanced-heading guten-UyfgMi"><h5 class="heading-subtitle">Book Now</h5><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Make an Appointment</span><span class="heading-focus"></span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-KYGmhc","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"positioningWidth":{"Desktop":{"point":"533","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-KYGmhc"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-keNpCs","type":4,"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"add4d57"},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-keNpCs">Opening Hours</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-eXVVkA","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-8"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="eXVVkA"><section class="wp-block-gutenverse-section guten-element guten-section guten-eXVVkA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":38},"elementId":"guten-GAr4IW","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GAr4IW"><div class="guten-column-wrapper" data-id="GAr4IW"><!-- wp:gutenverse/text-editor {"elementId":"guten-VZcfOM","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-VZcfOM"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Monday - Thursday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":62},"elementId":"guten-AbTIA5","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AbTIA5"><div class="guten-column-wrapper" data-id="AbTIA5"><!-- wp:gutenverse/icon-list {"elementId":"guten-0mTFQv","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-icon-list guten-0mTFQv"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-rxwyOB"} -->
<div class="guten-element guten-icon-list-item guten-rxwyOB"><a id="guten-rxwyOB"><i class="far fa-clock"></i><span class="list-text ">08.00 AM - 20.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vgaplA","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"top":{"type":"none","color":"","width":null},"right":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"bottom":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"},"left":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="vgaplA"><section class="wp-block-gutenverse-section guten-element guten-section guten-vgaplA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":30},"elementId":"guten-Zq5huQ","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Zq5huQ"><div class="guten-column-wrapper" data-id="Zq5huQ"><!-- wp:gutenverse/text-editor {"elementId":"guten-q8Ms6W","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-q8Ms6W"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Friday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":70},"elementId":"guten-A8zw4K","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-A8zw4K"><div class="guten-column-wrapper" data-id="A8zw4K"><!-- wp:gutenverse/icon-list {"elementId":"guten-2nFAsM","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-2nFAsM"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-DB1Xwn"} -->
<div class="guten-element guten-icon-list-item guten-DB1Xwn"><a id="guten-DB1Xwn"><i class="far fa-clock"></i><span class="list-text ">08.00 AM - 17.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-njQcNN","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"top":{"type":"none","color":"","width":null},"right":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"bottom":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"},"left":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="njQcNN"><section class="wp-block-gutenverse-section guten-element guten-section guten-njQcNN layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":30},"elementId":"guten-AJzXOB","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AJzXOB"><div class="guten-column-wrapper" data-id="AJzXOB"><!-- wp:gutenverse/text-editor {"elementId":"guten-YrkxQD","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-YrkxQD"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Saturday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":70},"elementId":"guten-RNVhaI","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RNVhaI"><div class="guten-column-wrapper" data-id="RNVhaI"><!-- wp:gutenverse/icon-list {"elementId":"guten-lnWfvM","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-lnWfvM"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-HhgDot"} -->
<div class="guten-element guten-icon-list-item guten-HhgDot"><a id="guten-HhgDot"><i class="far fa-clock"></i><span class="list-text ">09.00 AM - 14.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-hyOf40","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"top":{"type":"none","color":"","width":null},"right":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"bottom":{"type":"solid","color":{"type":"variable","id":"theme-8"},"width":"1"},"left":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="hyOf40"><section class="wp-block-gutenverse-section guten-element guten-section guten-hyOf40 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":30},"elementId":"guten-5TlCze","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5TlCze"><div class="guten-column-wrapper" data-id="5TlCze"><!-- wp:gutenverse/text-editor {"elementId":"guten-lEeqfK","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-lEeqfK"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sunday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":70},"elementId":"guten-awNMuK","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-awNMuK"><div class="guten-column-wrapper" data-id="awNMuK"><!-- wp:gutenverse/icon-list {"elementId":"guten-DuKfJm","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-5"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-DuKfJm"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-v6cV8W"} -->
<div class="guten-element guten-icon-list-item guten-v6cV8W"><a id="guten-v6cV8W"><i class="far fa-clock"></i><span class="list-text ">09.00 AM - 18.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-yyP7Bq","type":4,"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"add4d57","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":[]}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-yyP7Bq">Support</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-oHKWii","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element gutenverse-text-editor guten-oHKWii"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-6NMPI1","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
<div class="section-wrapper" data-id="6NMPI1"><section class="wp-block-gutenverse-section guten-element guten-section guten-6NMPI1 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-TTk6Q4","background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TTk6Q4"><div class="guten-column-wrapper" data-id="TTk6Q4"><!-- wp:gutenverse/icon-box {"elementId":"guten-HJ6hin","separateButtonLink":false,"title":"Email Address","titleTag":"h4","description":"support@domain.com\n\n","icon":"gtn gtn-envelope2-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":[]}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12.5"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"","bottom":"","left":""}},"Tablet":[]},"iconStyleMode":"color","iconColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"theme-4"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"0","bottom":"6","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"titleColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"add4d57","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":[]},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-5"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"zIndex":{"Tablet":0},"parentSelector":".guten-HJ6hin:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-HJ6hin guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-envelope2-light"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Email Address</h4><p class="icon-box-description">support@domain.com

</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-YSDdKh","background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YSDdKh"><div class="guten-column-wrapper" data-id="YSDdKh"><!-- wp:gutenverse/icon-box {"elementId":"guten-6CcWw5","separateButtonLink":false,"title":"Phone Number","titleTag":"h3","description":"(+62)81 422 7509\n","icon":"gtn gtn-phone1-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[]},"containerBackgroundHover":{"type":"default","color":[],"image":[]},"containerBorder":{"top":{"type":"solid","width":"0"},"right":{"type":"solid","width":"0"},"bottom":{"type":"solid","width":"0"},"left":{"type":"solid","width":"0"},"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"4","right":"","bottom":"","left":""}},"Tablet":[]},"iconColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"theme-4"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"0","bottom":"6","left":"0"}}},"titleColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"add4d57"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-5"},"descTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Tablet":0},"parentSelector":".guten-6CcWw5:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-6CcWw5 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-phone1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Phone Number</h3><p class="icon-box-description">(+62)81 422 7509
</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
