<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Home Gutenverse Hero', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-hm45vo","background":{"type":"default","color":"","image":{"Desktop":{"id":208,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/hero-quinnie-plastic-surgery.jpg"}},"position":{"Desktop":"bottom right","Tablet":"center center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom","Tablet":"cover","Mobile":"cover"},"videoPlayOnMobile":false,"blendMode":{"Desktop":"normal"},"width":{"Desktop":{"unit":"%","point":"95"}},"xposition":{"Mobile":{"point":"-300","unit":"px"}},"yposition":{"Mobile":{"point":"1","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-1"}},"opacity":"0.12","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","right":"0","bottom":"320","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"180","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"","left":"","top":"80","bottom":"120"}}}} -->
<div class="section-wrapper" data-id="hm45vo"><section class="wp-block-gutenverse-section guten-element guten-section guten-hm45vo layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":57,"Mobile":null},"elementId":"guten-MpIS1d","background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MpIS1d"><div class="guten-column-wrapper" data-id="MpIS1d"><!-- wp:gutenverse/heading {"elementId":"guten-sfvqPc","type":1,"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"quinnie_typo_primary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"spacing":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-sfvqPc animated guten-element-hide desktop-fadeInLeft">We Provide Best Plastic and Reconstructive Surgery For You</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-QWqolL","textColor":{"type":"variable","id":"theme-5"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":200},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"520","unit":"px"},"Tablet":{"point":"373","unit":"px"},"Mobile":{"point":"228","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-QWqolL animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-2CrNtJ","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="2CrNtJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-2CrNtJ layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":45,"Mobile":100},"elementId":"guten-4eIAde","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":""}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4eIAde"><div class="guten-column-wrapper" data-id="4eIAde"><!-- wp:gutenverse/button {"elementId":"guten-5vr72S","content":"Get Started","url":"#","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"38","left":"38"}},"Mobile":{"unit":"px","dimension":{"top":"16","bottom":"16","right":"36","left":"36"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[]},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-4"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":""}}},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":400},"color":{"type":"variable","id":"3eec7ca"},"typography":{"type":"variable","id":"3bcc232"},"hoverTextColor":{"type":"variable","id":"primary"},"positioningType":{"Mobile":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-5vr72S"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Get Started</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":55,"Mobile":100},"elementId":"guten-9BhTqL","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"5"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":600}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9BhTqL animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="9BhTqL"><!-- wp:gutenverse/icon-box {"elementId":"guten-P0lQN6","url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"icon":"gtn gtn-play","iconSize":{"Desktop":"18","Mobile":"16"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"19","right":"17","bottom":"19","left":"21"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"14","bottom":"16","left":"18"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconStyleMode":"color","iconColor":{"type":"variable","id":"white"},"iconHoverColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"theme-4"},"iconHoverBgColor":{"type":"variable","id":"theme-3"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconBoxShadow":{"vertical":"0","color":{"r":0,"g":0,"b":0,"a":0},"horizontal":"0"},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":0},"positioningType":{"Desktop":"inline"},"parentSelector":".guten-P0lQN6:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-P0lQN6 guten-icon-box icon-position-undefined"><a class="" href="#"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-play"></i></div></div></div></a></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/button {"elementId":"guten-u6wYfb","content":"Watch Video","alignButton":{"Desktop":"right"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":253,"g":158,"b":1,"a":0},"image":[]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverTextColor":{"type":"variable","id":"theme-4"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-u6wYfb"><a class="guten-button guten-button-sm" href="#"><span>Watch Video</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
