<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Gutenverse Why Choose Us', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-unV93C","background":{"type":"default","color":[],"image":[],"position":[],"repeat":[],"size":[],"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Desktop":2,"Tablet":0},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="unV93C"><section class="wp-block-gutenverse-section guten-element guten-section guten-unV93C layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-aJScyp","background":{"type":"default","color":[],"image":{"Desktop":{"id":323,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/view-from-above-rejuvenation-of-beautiful-woman-enjoying-cosmetology-procedures-in-beauty-salon-quinnie.webp"}},"position":{"Desktop":"custom","Tablet":"center center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"0","unit":"px"},"Mobile":{"point":"1","unit":"px"}},"xposition":{"Desktop":{"point":"-380","unit":"px"},"Mobile":{"point":"-530","unit":"px"}}},"verticalAlign":{"Desktop":"flex-end","Mobile":"flex-end"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-50"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aJScyp"><div class="guten-column-wrapper" data-id="aJScyp"><!-- wp:gutenverse/spacer {"elementId":"guten-ILvVAK","space":{"Desktop":{"unit":"px","point":"389"}},"background":{"type":"default","color":[],"image":[]}} -->
<div class="guten-element guten-spacer guten-ILvVAK"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-miFAoA","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Tablet":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="miFAoA"><section class="wp-block-gutenverse-section guten-element guten-section guten-miFAoA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-L0A4Pf","background":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[],"position":[],"repeat":[],"size":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"8","right":"10","bottom":"11","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"30","left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-L0A4Pf animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="L0A4Pf"><!-- wp:gutenverse/heading {"elementId":"guten-Tbv17C","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"4ac71db"},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-Tbv17C">Schedule an Appointment</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-xGW6Gj","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element gutenverse-text-editor guten-xGW6Gj"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consecte adipiscing elit, sed do eiusmod tempor incididunt ut labore</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-mr6zGR","content":"Explore Service","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0},"image":[]},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"background":{"type":"default","color":[],"image":[]},"color":{"type":"variable","id":"theme-4"},"iconColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"f04d15a"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"}} -->
<div class="guten-element guten-button-wrapper guten-mr6zGR"><a class="guten-button guten-button-sm" href="#"><span>Explore Service</span><i class="fa-lg gtn gtn-right-arrow-light"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-uI8f71","background":{"type":"default","color":[],"image":[]},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uI8f71 hide-mobile"><div class="guten-column-wrapper" data-id="uI8f71"></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-5S55RW","background":{"type":"default","color":{"type":"variable","id":"theme-3"},"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"15","right":"15","bottom":"20","left":"15"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"50","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"80","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5S55RW"><div class="guten-column-wrapper" data-id="5S55RW"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-hEEPsz","subTag":"h5","openDynamic":"guten-gYhGhR","text":"We Offers A Complete Range Of Plastic Surgery Services","focusText":"","subText":"Why Choose Us","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"0d5454c","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"subPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"540","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-hEEPsz"><h5 class="heading-subtitle">Why Choose Us</h5><div class="heading-section "><h2 class="heading-title"><span class="heading-title">We Offers A Complete Range Of Plastic Surgery Services</span><span class="heading-focus"></span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-nltF79","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"500"}}} -->
<div class="guten-element gutenverse-text-editor guten-nltF79"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud xercitation ullamco</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-wFohyA","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="wFohyA"><section class="wp-block-gutenverse-section guten-element guten-section guten-wFohyA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-mO2Hx8","background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mO2Hx8"><div class="guten-column-wrapper" data-id="mO2Hx8"><!-- wp:gutenverse/fun-fact {"elementId":"guten-zZIwQ6","iconType":"none","icon":"gtn gtn-team-1-line","iconColor":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconSize":{"Desktop":"","Mobile":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"prefix":"","number":"92","suffix":"","title":"Succesful Surgery","titleTag":"h3","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"12"},"superSpace":{"Desktop":"4"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"white"}},"titleColor":{"Desktop":{"type":"variable","id":"white"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"a89b1a5","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"numberBottomSpace":{"Desktop":"16"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"5","left":"-10"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"zIndex":{"Tablet":1}} -->
<div class="guten-element guten-zZIwQ6 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="92" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><h3 class="title">Succesful Surgery</h3></div></div></div>
<!-- /wp:gutenverse/fun-fact -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-VZ8QkW","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-VZ8QkW"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-nwSBwm","background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nwSBwm"><div class="guten-column-wrapper" data-id="nwSBwm"><!-- wp:gutenverse/fun-fact {"elementId":"guten-GN7KRi","iconType":"none","icon":"gtn gtn-team-1-line","iconColor":{"Desktop":{"type":"variable","id":"secondary"}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconSize":{"Desktop":"","Mobile":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"prefix":"","number":"90","suffix":"","title":"Diagnosis Accuracy","titleTag":"h3","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"12"},"superSpace":{"Desktop":"4"},"superAlign":{"Desktop":"super"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"white"}},"titleColor":{"Desktop":{"type":"variable","id":"white"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"a89b1a5","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"numberBottomSpace":{"Desktop":"16"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"5","left":"-10"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"zIndex":{"Mobile":1}} -->
<div class="guten-element guten-GN7KRi guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="90" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><h3 class="title">Diagnosis Accuracy</h3></div></div></div>
<!-- /wp:gutenverse/fun-fact -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Xm1vDw","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-Xm1vDw"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-JlGemj","content":"Start Consultation","alignButton":{"Desktop":"left","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"26","bottom":"15","left":"26"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"38","left":"38"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-4"},"image":[]},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"3eec7ca"},"typography":{"type":"variable","id":"f04d15a"},"hoverTextColor":{"type":"variable","id":"theme-4"}} -->
<div class="guten-element guten-button-wrapper guten-JlGemj"><a class="guten-button guten-button-sm" href="#"><span>Start Consultation</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => true,
);
