<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie About Gutenverse Second CTA', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-0cKIE9","background":{"type":"default","color":[],"image":{"Desktop":{"id":44,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/woman-at-the-plastic-surgeon.jpg"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-3"}},"opacity":"0.8","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","right":"0","bottom":"120","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"0","bottom":"80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"60","left":"0"}}}} -->
<div class="section-wrapper" data-id="0cKIE9"><section class="wp-block-gutenverse-section guten-element guten-section guten-0cKIE9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-zksjXO","background":{"type":"default","color":[],"image":[]},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"5"}}},"animation":{"type":{"Desktop":"none","Tablet":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-zksjXO"><div class="guten-column-wrapper" data-id="zksjXO"><!-- wp:gutenverse/icon-box {"elementId":"guten-YSXw8G","url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"icon":"gtn gtn-play","iconSize":{"Desktop":"22","Mobile":"20"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"24","right":"22","bottom":"24","left":"26"}},"Tablet":{"unit":"px","dimension":{"top":"22","bottom":"22","right":"20","left":"24"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"18","bottom":"20","left":"22"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"25"}}},"iconStyleMode":"color","iconColor":{"type":"variable","id":"theme-4"},"iconHoverColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"white"},"iconHoverBgColor":{"type":"variable","id":"theme-4"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"iconBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconBorderHoverResponsive":{"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Tablet":0,"Desktop":0},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"positioningType":{"Desktop":"inline"},"parentSelector":".guten-YSXw8G:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-YSXw8G animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-undefined"><a class="" href="#"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-play"></i></div></div></div></a></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/heading {"elementId":"guten-maoxMz","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200},"positioningType":{"Tablet":"default"},"positioningWidth":{"Tablet":{"point":"524","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-maoxMz animated guten-element-hide desktop-fadeInUp">Our Motive is Helping Patients From Around The Globe</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-D75mDg","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":300},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"595","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-D75mDg animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-DHoejU","content":"Start Consultation","alignButton":{"Desktop":"center","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"26","bottom":"15","left":"26"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"38","left":"38"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-4"},"image":[]},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":500},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverTextColor":{"type":"variable","id":"theme-4"}} -->
<div class="guten-element guten-button-wrapper guten-DHoejU"><a class="guten-button animated guten-element-hide desktop-fadeInUp guten-button-sm" href="#"><span>Start Consultation</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
