<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie-404-gutenverse-hero', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"800"},"elementId":"guten-a3LM0o","background":{"type":"default","color":"","image":{"Desktop":{"id":702,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/treatment-404-page-quinnie.webp"}},"position":{"Desktop":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-3"}},"opacity":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","right":"0","bottom":"200","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"120","right":"0","bottom":"120","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"110","right":"10","bottom":"120","left":"10"}}}} -->
<div class="section-wrapper" data-id="a3LM0o"><section class="wp-block-gutenverse-section guten-element guten-section guten-a3LM0o layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-PQMFD8","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PQMFD8"><div class="guten-column-wrapper" data-id="PQMFD8"><!-- wp:gutenverse/heading {"elementId":"guten-SNBRb7","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"8c51f57"},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20","right":"0","bottom":"-20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-20","right":"0","bottom":"-25","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"-10"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-SNBRb7">404</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-peavqy","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-peavqy">Page Not Found</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-yjsqJn","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":[]}} -->
<div class="guten-element gutenverse-text-editor guten-yjsqJn"><div class="text-content-inner"><!-- wp:paragraph -->
<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-umkFnl","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"","right":"","bottom":""}},"Tablet":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputPlaceholder":"Search","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"32","right":"32","top":"18","bottom":"18"}},"Mobile":{"unit":"px","dimension":{"bottom":"16","top":"16","right":"30","left":"30"}},"Tablet":[]},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":[]},"inputHeight":{"Desktop":"","Mobile":""},"inputWidth":{"Desktop":{"unit":"px","point":"420"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"50","right":"0","top":"50","bottom":"0"}}},"all":{"type":"none","width":0,"color":""}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"Tablet":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"left":""}},"Mobile":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"alignContent":{"Mobile":"center","Desktop":"center"},"className":"guten-icon"} -->
<div class="guten-element guten-umkFnl guten-search guten-icon"><form class="gutenverse-search-form"><div class="search-input-container"><input type="search" placeholder="Search" name="s" class="gutenverse-search gutenverse-search-input"/></div><!-- wp:gutenverse/button {"elementId":"guten-zqixci","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"buttonHeight":{"Desktop":"62","Mobile":"52"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"buttonBackground":{"color":{"type":"variable","id":"theme-4"},"type":"default","position":{"Mobile":"default"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"50","left":"0"}}},"all":{"type":"none","width":null,"color":""}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"none"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"px","point":"320"}}} -->
<div class="guten-element guten-button-wrapper guten-zqixci"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
