<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Gutenverse Appointment', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-bjjI2h","background":{"type":"default","color":[],"image":{"Desktop":{"id":23,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/cosmetician-gives-chin-quinnie.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-3"}},"opacity":"0.85","margin":{"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="bjjI2h"><section class="wp-block-gutenverse-section guten-element guten-section guten-bjjI2h layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-xRJEc6","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"top"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"80","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"40","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xRJEc6"><div class="guten-column-wrapper" data-id="xRJEc6"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-jS7AC5","subTag":"h5","text":"Make an Appointment","focusText":"","subText":"Book Now","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"mainPadding":{"Desktop":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"0d5454c","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"17"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"subMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"subPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-advanced-heading guten-jS7AC5"><h5 class="heading-subtitle">Book Now</h5><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Make an Appointment</span><span class="heading-focus"></span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-8rFL0f","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-8rFL0f"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius tempor ut incididunt labore et dolore magna aliqua. Ut enim adiqua minim veniam quis nostrud exercitation ullamco incididunt magna aliqua veniam.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-Tbq0j7","type":4,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"add4d57","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-Tbq0j7">Opening Hours</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-0xozO5","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-6"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="0xozO5"><section class="wp-block-gutenverse-section guten-element guten-section guten-0xozO5 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":40},"elementId":"guten-DHQfR3","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DHQfR3"><div class="guten-column-wrapper" data-id="DHQfR3"><!-- wp:gutenverse/text-editor {"elementId":"guten-Zvsrbc","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-Zvsrbc"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Monday - Thursday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":60},"elementId":"guten-tvUciS","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tvUciS"><div class="guten-column-wrapper" data-id="tvUciS"><!-- wp:gutenverse/icon-list {"elementId":"guten-pr7TN6","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-pr7TN6"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-L13lFl"} -->
<div class="guten-element guten-icon-list-item guten-L13lFl"><a id="guten-L13lFl"><i class="far fa-clock"></i><span class="list-text ">08.00 AM - 20.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vnOf9H","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"top":{"type":"none","color":{"type":"variable","id":"theme-6"},"width":null},"right":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"bottom":{"type":"solid","color":{"type":"variable","id":"theme-6"},"width":"1"},"left":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="vnOf9H"><section class="wp-block-gutenverse-section guten-element guten-section guten-vnOf9H layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":40},"elementId":"guten-TPyT4D","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"default"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TPyT4D"><div class="guten-column-wrapper" data-id="TPyT4D"><!-- wp:gutenverse/text-editor {"elementId":"guten-tHJAmd","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-tHJAmd"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Friday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":60},"elementId":"guten-vgOVr3","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vgOVr3"><div class="guten-column-wrapper" data-id="vgOVr3"><!-- wp:gutenverse/icon-list {"elementId":"guten-McecA2","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-McecA2"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-eifX2J"} -->
<div class="guten-element guten-icon-list-item guten-eifX2J"><a id="guten-eifX2J"><i class="far fa-clock"></i><span class="list-text ">08.00 AM - 17.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-T4Ks6g","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-6"}}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="T4Ks6g"><section class="wp-block-gutenverse-section guten-element guten-section guten-T4Ks6g layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":40},"elementId":"guten-J5Lwb5","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"default","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-J5Lwb5"><div class="guten-column-wrapper" data-id="J5Lwb5"><!-- wp:gutenverse/text-editor {"elementId":"guten-CCh4pT","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-CCh4pT"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Saturday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":60},"elementId":"guten-9CeGlj","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9CeGlj"><div class="guten-column-wrapper" data-id="9CeGlj"><!-- wp:gutenverse/icon-list {"elementId":"guten-Prs4db","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-Prs4db"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-8hJFRe"} -->
<div class="guten-element guten-icon-list-item guten-8hJFRe"><a id="guten-8hJFRe"><i class="far fa-clock"></i><span class="list-text ">09.00 AM - 14.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-NIQy0Y","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false},"border":{"top":{"type":"none","color":"","width":null},"right":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"bottom":{"type":"solid","color":{"type":"variable","id":"theme-6"},"width":"1"},"left":{"type":"solid","color":{"r":255,"g":255,"b":255,"a":0.10980392156862745},"width":"0"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="NIQy0Y"><section class="wp-block-gutenverse-section guten-element guten-section guten-NIQy0Y layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":40},"elementId":"guten-zjDXuJ","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-zjDXuJ"><div class="guten-column-wrapper" data-id="zjDXuJ"><!-- wp:gutenverse/text-editor {"elementId":"guten-0Wh7Rg","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"8","top":"8","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-0Wh7Rg"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sunday</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":60},"elementId":"guten-DbUc4P","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DbUc4P"><div class="guten-column-wrapper" data-id="DbUc4P"><!-- wp:gutenverse/icon-list {"elementId":"guten-A17nrm","alignList":{"Desktop":"flex-end"},"iconColor":{"type":"variable","id":"theme-4"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"12"},"textTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","top":"8"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list guten-A17nrm"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-emc556"} -->
<div class="guten-element guten-icon-list-item guten-emc556"><a id="guten-emc556"><i class="far fa-clock"></i><span class="list-text ">09.00 AM - 18.00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-Neu0MG","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"position":[],"repeat":[],"size":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":"23.999999999999996","g":"22.000000000000004","b":"43","a":"0.14"},"horizontal":"0","vertical":"3","blur":"30","spread":"0"},"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"-23","left":"8"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-100","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"-100","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"zIndex":{"Desktop":2,"Tablet":0},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Neu0MG animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="Neu0MG"><!-- wp:gutenverse/form-builder {"elementId":"guten-wtepQf","formId":{"label":"Form Appointment","value":1039}} -->
<form style="display:none" class="guten-element guten-form-builder guten-wtepQf" data-form-id="1039"><!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-3haLgc"} -->
<div class="section-wrapper" data-id="3haLgc"><section class="wp-block-gutenverse-section guten-element guten-section guten-3haLgc layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-GmyrJ3"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GmyrJ3"><div class="guten-column-wrapper" data-id="GmyrJ3"><!-- wp:gutenverse/form-input-text {"elementId":"guten-5sX1ez","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"text"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-5sX1ez hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-hLHoZn","margin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="hLHoZn"><section class="wp-block-gutenverse-section guten-element guten-section guten-hLHoZn layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-iPtZrS","margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-iPtZrS"><div class="guten-column-wrapper" data-id="iPtZrS"><!-- wp:gutenverse/form-input-email {"elementId":"guten-FYfcN4","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-FYfcN4 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-W6reUq","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-W6reUq"><div class="guten-column-wrapper" data-id="W6reUq"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-2fkPVH","showLabel":false,"showHelper":false,"labelWidth":{"Desktop":"62"},"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"inputPlaceholder":"Your Phone Number","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-2fkPVH hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Phone Number" name="input-phone" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="\+[0-9]+[0-9\s\-]*"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-select {"elementId":"guten-jrH04o","showLabel":false,"inputPlaceholder":"Select Services","showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"selectOptions":[{"value":"option-1","label":"Rhinoplasty","_key":"r8zD6S"},{"value":"option-2","label":"Botox Injection","_key":"QrpxPX"},{"value":"option-3","label":"Breast Implant","_key":"t3DH9m"},{"value":"option-3","label":"Facelift","_key":"raQxnl"},{"value":"option-3","label":"Body Shaping","_key":"qTCzlR"},{"value":"option-3","label":"Buttocks Reshape","_key":"hQyqqh"}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","right":"23","bottom":"13","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"placeholderBgColor":{"Desktop":{"type":"variable","id":"white"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]}},"choicesColorNormal":{"Desktop":{"type":"variable","id":"theme-5"}},"choicesColorHover":{"Desktop":{"type":"variable","id":"white"}},"choicesBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"choicesBgColorHover":{"Desktop":{"type":"variable","id":"theme-4"}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-jrH04o hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="input-select" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Select Services</option><option value="option-1">Rhinoplasty</option><option value="option-2">Botox Injection</option><option value="option-3">Breast Implant</option><option value="option-3">Facelift</option><option value="option-3">Body Shaping</option><option value="option-3">Buttocks Reshape</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select -->

<!-- wp:gutenverse/form-input-date {"elementId":"guten-bPKPLO","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"inputPlaceholder":"Select Date","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-date guten-form-input guten-input-position-top guten-bPKPLO hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;date&quot;}" data-date="{&quot;dateFormat&quot;:&quot;F j, Y&quot;}" placeholder="Select Date" name="input-date" class="gutenverse-input gutenverse-input-date" type="text"/><div class="validation-error"></div></div></div>
<!-- /wp:gutenverse/form-input-date -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-IwMzPc","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"inputHeight":{"Desktop":"200"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"13","bottom":"13","right":"23","left":"23"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"10"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-5"}},"inputTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-3"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-IwMzPc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-hp3k1U","content":"Make Appointment","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-4"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"color":{"type":"variable","id":"3eec7ca"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"16","bottom":"16"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-hp3k1U"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Make Appointment</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-Ma9crS","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"videoPlayOnMobile":false},"margin":{"Tablet":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"30","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"30","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="Ma9crS"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ma9crS layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":48.99,"Tablet":null},"elementId":"guten-cHSyMl","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"15"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cHSyMl"><div class="guten-column-wrapper" data-id="cHSyMl"><!-- wp:gutenverse/logo-slider {"elementId":"guten-Bdd9fu","logos":[{"title":"One","_key":"t8mtWm","src":{"id":498,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/tree.png"},"lazyLoad":true},{"title":"Two","_key":"H9WUE0","src":{"id":499,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/lifecare.png"},"lazyLoad":true},{"title":"Three","_key":"wFKVNl","src":{"id":500,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/heartcare.png"},"lazyLoad":true}],"imageFit":{"Desktop":"cover"},"imagePadding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"imageMargin":{"Desktop":[],"Tablet":[]},"imageHoverPadding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":[]},"imageHoverMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageBorder":{"radius":{"Desktop":[]}},"imageBorderResponsive":{"Tablet":{"radius":[]}},"imageBorderHover":{"radius":{"Desktop":[]}},"imageBorderHoverResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"spacing":{"Desktop":""},"itemShowed":{"Desktop":"3","Tablet":"3","Mobile":"2"},"autoplay":true,"loop":true,"dotsSpacingVertical":{"Desktop":"1"},"dotsWidth":{"Desktop":""},"dotsRadius":{"Desktop":[]},"dotsActiveWidth":{"Desktop":""},"dotsActiveHeight":{"Desktop":""},"dotsActiveRadius":{"Desktop":[]},"arrowPadding":{"Desktop":[]},"arrowMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[]}},"opacity":"0.35","logoWrapperMargin":{"Desktop":[],"Tablet":[]},"logoWrapperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-Bdd9fu arrow-bottom-edge"><div class="client-list"><div id="guten-Bdd9fu" class="swiper-container" data-loop="true" data-autoplay="true" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:3}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/tree.png" alt="One" loading="lazy"/><img class="hover-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/tree.png" alt="One" loading="lazy"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/lifecare.png" alt="Two" loading="lazy"/><img class="hover-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/lifecare.png" alt="Two" loading="lazy"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/heartcare.png" alt="Three" loading="lazy"/><img class="hover-image" src="' . esc_url( QUINNIE_URI ) . 'assets/img/heartcare.png" alt="Three" loading="lazy"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":51.01,"Tablet":null},"elementId":"guten-3MDmQ7","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"hideTablet":true,"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3MDmQ7 hide-tablet hide-mobile"><div class="guten-column-wrapper" data-id="3MDmQ7"></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => true,
);
