<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Home Gutenverse CTA', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"height":{"Desktop":{"unit":"vh","point":"75"},"Tablet":{"unit":"vh","point":"60"},"Mobile":{"unit":"vh","point":"50"}},"elementId":"guten-IzsihY","heightControl":"min","background":{"videoPlayOnMobile":false,"type":"video","videoLink":"https://www.youtube.com/watch?v=j0_aDe-xvIQ","videoStartTime":"40","videoEndTime":"80","videoPlayOnce":false,"videoImage":{"Desktop":{"id":702,"image":"' . esc_url( QUINNIE_URI ) . 'assets/img/treatment-404-page-quinnie.webp"}}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"theme-3"}},"opacity":"0.5","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"bottom":"50","top":"","right":"10","left":"10"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="IzsihY"><section class="wp-block-gutenverse-section guten-element guten-section guten-IzsihY layout-boxed align-stretch"><div class="guten-video-background" data-property="{&quot;url&quot;:&quot;https://www.youtube.com/watch?v=j0_aDe-xvIQ&quot;,&quot;class&quot;:&quot;guten-video-bg-wrapper&quot;,&quot;width&quot;:&quot;100%&quot;,&quot;height&quot;:&quot;100%&quot;,&quot;playing&quot;:true,&quot;muted&quot;:true,&quot;loop&quot;:true,&quot;playsinline&quot;:true,&quot;style&quot;:{&quot;zIndex&quot;:0,&quot;top&quot;:0,&quot;left&quot;:0,&quot;position&quot;:&quot;absolute&quot;,&quot;overflow&quot;:&quot;hidden&quot;,&quot;pointerEvents&quot;:&quot;none&quot;},&quot;config&quot;:{&quot;youtube&quot;:{&quot;playerVars&quot;:{&quot;showinfo&quot;:0,&quot;start&quot;:40,&quot;end&quot;:80}}}}"></div><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-ct5OGM","verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end","Mobile":"flex-end"},"horizontalAlign":{"Desktop":"flex-start"},"margin":{"Desktop":{"unit":"%","dimension":{"right":"55"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ct5OGM"><div class="guten-column-wrapper" data-id="ct5OGM"><!-- wp:gutenverse/heading {"elementId":"guten-Rs9RnU","textAlign":{"Desktop":"left","Tablet":"left","Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"positioningType":{"Tablet":"custom","Desktop":"full"},"positioningWidth":{"Tablet":{"point":"564","unit":"px"},"Desktop":{"point":"506","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Rs9RnU">Providing World-Class Care to Patients Around the World</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-rQGwUC","content":"Start Consultation","url":"#","alignButton":{"Desktop":"left","Mobile":"center","Tablet":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"26","bottom":"15","left":"26"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"38","left":"38"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-4"},"image":[]},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"3bcc232","font":{"label":"Inter","value":"Inter","type":"google"},"weight":"500","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":[]},"hoverTextColor":{"type":"variable","id":"theme-4"}} -->
<div class="guten-element guten-button-wrapper guten-rQGwUC"><a class="guten-button guten-button-sm" href="#"><span>Start Consultation</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
