<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Quinnie Home Gutenverse Funfact', 'quinnie' ),
	'categories' => array( 'quinnie-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1290},"elementId":"guten-C3wE6r","background":{"type":"default","color":{"type":"variable","id":"white"},"image":[],"videoPlayOnMobile":false},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="section-wrapper" data-id="C3wE6r"><section class="wp-block-gutenverse-section guten-element guten-section guten-C3wE6r layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-WnMJOn","background":{"type":"default","color":{"r":253,"g":240,"b":224,"a":1},"image":[],"position":[],"repeat":[],"size":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"30","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-WnMJOn"><div class="guten-column-wrapper" data-id="WnMJOn"><!-- wp:gutenverse/section {"width":{"Desktop":1290},"isChild":true,"gap":"no","elementId":"guten-pOqjOC","background":{"type":"default","color":[],"image":[],"videoPlayOnMobile":false}} -->
<div class="section-wrapper" data-id="pOqjOC"><section class="wp-block-gutenverse-section guten-element guten-section guten-pOqjOC layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50,"Tablet":null},"elementId":"guten-zPT9Ce","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-zPT9Ce"><div class="guten-column-wrapper" data-id="zPT9Ce"><!-- wp:gutenverse/fun-fact {"elementId":"guten-vAfwuS","icon":"gtn gtn-team-1-line","iconColor":{"Desktop":{"type":"variable","id":"theme-4"}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48","Mobile":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"prefix":"","number":"1452","suffix":"","title":"Happy Patients","showSupper":true,"superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"baseline"},"numberColor":{"Desktop":{"type":"variable","id":"theme-3"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-5"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Tablet":1}} -->
<div class="guten-element guten-vAfwuS guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-1-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="1452" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Happy Patients</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-ezI8Qv","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ezI8Qv"><div class="guten-column-wrapper" data-id="ezI8Qv"><!-- wp:gutenverse/fun-fact {"elementId":"guten-cTxxIJ","icon":"gtn gtn-app-light","iconColor":{"Desktop":{"type":"variable","id":"theme-4"}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"prefix":"","number":"342","suffix":"","title":"Online Appointments","titleTag":"h5","showSupper":true,"superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"baseline"},"numberColor":{"Desktop":{"type":"variable","id":"theme-3"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-5"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"numberBottomSpace":{"Desktop":"5"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Tablet":1}} -->
<div class="guten-element guten-cTxxIJ guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-app-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="342" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><h5 class="title">Online Appointments</h5></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-EedmZm","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"15"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EedmZm"><div class="guten-column-wrapper" data-id="EedmZm"><!-- wp:gutenverse/fun-fact {"elementId":"guten-iYmMXt","icon":"gtn gtn-badge","iconColor":{"Desktop":{"type":"variable","id":"theme-4"}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"prefix":"","number":"15","suffix":"","title":"Years of Experience","titleTag":"h5","showSupper":true,"superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"baseline"},"numberColor":{"Desktop":{"type":"variable","id":"theme-3"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-5"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"numberBottomSpace":{"Desktop":"5"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Tablet":[]},"padding":{"Tablet":[]},"zIndex":{"Tablet":1}} -->
<div class="guten-element guten-iYmMXt guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-badge"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="15" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><h5 class="title">Years of Experience</h5></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-nN0d8p","background":{"type":"default","color":[],"image":[]},"verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"15"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nN0d8p"><div class="guten-column-wrapper" data-id="nN0d8p"><!-- wp:gutenverse/fun-fact {"elementId":"guten-dDQz9n","icon":"gtn gtn-doctor-light","iconColor":{"Desktop":{"type":"variable","id":"theme-4"}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"prefix":"","number":"72","suffix":"","title":"Doctors and Staff","titleTag":"h5","showSupper":true,"superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"3"},"superAlign":{"Desktop":"baseline"},"numberColor":{"Desktop":{"type":"variable","id":"theme-3"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-5"}},"numberTypography":{"type":"variable","id":"quinnie_typo_secondary","font":{"label":"Lato","value":"Lato","type":"google"},"weight":"600","size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"spacing":[]},"titleTypography":{"type":"variable","id":"quinnie_typo_text","font":{"label":"Heebo","value":"Heebo","type":"google"},"weight":"400","size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"spacing":[]},"numberBottomSpace":{"Desktop":"5"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"background":{"type":"default","color":[],"image":[]},"margin":{"Tablet":[]},"padding":{"Tablet":[]},"zIndex":{"Tablet":1}} -->
<div class="guten-element guten-dDQz9n guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-doctor-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="72" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><h5 class="title">Doctors and Staff</h5></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
